# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# Proxy /gas to your Apps Script deployment (works for GET and POST)
[[redirects]]
  from = "/gas"
  to = "https://script.google.com/macros/s/AKfycbyWCzApXWxr5gr5DTYyDN8QDheGKCGbtZ-XxILuJxmeWITiK0vhGVLX1RYhUcFNTQlC/exec"
  status = 200
  force = true
  
# SPA routing - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
